export const ADD_CUSTOMER_REQUESTED = 'ADD_CUSTOMER_REQUESTED';
export const ADD_CUSTOMER_SUCCEEDED = 'ADD_CUSTOMER_SUCCEEDED';
export const ADD_CUSTOMER_FAILED = 'ADD_CUSTOMER_FAILED';
export const ADD_HOBBY_REQUESTED = 'ADD_HOBBY_REQUESTED';
